### PR TITLE
Api v1

### PR DESCRIPTION
**Pull request by Qadriyah**
Hey guys, your feed back is most welcome
@CandySusan 
@FahdJamy
@lubwamabenja
@bearded7
@bekeplar
@BarnaTB
@armstrongsouljah
@oma0256

### CODE REVIEW

**Comment by armstrongsouljah** [comment]
Implementation seems okay, although my recommendation is that you try and modularise your functions, some are a bit lengthy.

**Comment by bekeplar** [comment]
you functions are making sense though you need to use modules,,great work

**Comment by Qadriyah** [comment]
@armstrongsouljah  True man and i have tried to work on some of them

**Comment by mariamiah** [comment]
Yes I think the work is okay

**Comment by bearded7** [comment]
Wow! I like your landing page!
Your work tree is okay, you have minimized code duplication and have set a demonstrated high levels of understanding of this project.
I like how you have separated your tests!
There is lots someone can learn from you

**Comment by Qadriyah** [comment]
Thanks Douglas, I have been trying to work on the documentation using swagger but it's another project of it's own

**Pull request merged**
