### PR TITLE
Feat attendant profile 161199803

### PR DESCRIPTION
**Pull request by Qadriyah**
@BarnaTB
@bekeplar
@armstrongsouljah
@RLubwama
@fahadmak
@mwinel
@codjoero

### CODE REVIEW

**Comment by armstrongsouljah** [comment]
Nice going on the ui, my recommend is that, on the login page, move the validations to `<span></span>` instead of alert(), also when a user doesn't enter anything, they should not be allowed to just login. So in this case you'd have to prevent the default behavior of the form. 
Then, you could also use one form to process the login details and then send the user to their respective dashboard based on input details. All in all. Good work.

**Comment by Qadriyah** [comment]
Point noted

**Comment by probuse** [comment]
@Qadriyah this page  [](https://qadriyah.github.io/store-manager/UI/admin/settings.html) is confusing,
I can see it is under a menu called settings, inside i can see New Product, the form has a heading of New Attendant, then system users. 
I think it would be more use friendly if you did a single thing in a page.
The **settings menu does not say what is going on in the page**, you could **change the menu to store attendants**, **change New Product to New Attendant** and **instead of showing system users, you could show a list of attendants.**
Otherwise great work, keep it up

**Comment by probuse** [comment]
> Nice going on the ui, my recommend is that, on the login page, move the validations to `<span></span>` instead of alert(), also when a user doesn't enter anything, they should not be allowed to just login. So in this case you'd have to prevent the default behavior of the form.
> Then, you could also use one form to process the login details and then send the user to their respective dashboard based on input details. All in all. Good work.

@armstrongsouljah I thought we are implementing only the UI and how we will navigate from one page to another, do we have to be concerned with the logic at this point?

**Comment by Qadriyah** [comment]
> > Nice going on the ui, my recommend is that, on the login page, move the validations to `<span></span>` instead of alert(), also when a user doesn't enter anything, they should not be allowed to just login. So in this case you'd have to prevent the default behavior of the form.
> > Then, you could also use one form to process the login details and then send the user to their respective dashboard based on input details. All in all. Good work.
> 
> @armstrongsouljah I thought we are implementing only the UI and how we will navigate from one page to another, do we have to be concerned with the logic at this point?



> > Nice going on the ui, my recommend is that, on the login page, move the validations to `<span></span>` instead of alert(), also when a user doesn't enter anything, they should not be allowed to just login. So in this case you'd have to prevent the default behavior of the form.
> > Then, you could also use one form to process the login details and then send the user to their respective dashboard based on input details. All in all. Good work.
> 
> @armstrongsouljah I thought we are implementing only the UI and how we will navigate from one page to another, do we have to be concerned with the logic at this point?

We are actually not implementing the core functionality, we are just working on the ui

**Comment by armstrongsouljah** [comment]
@probuse, you can still navigate between pages using clientside code. Thats where `javascript` comes in to help you emulate the functionality.

**Pull request merged**
